//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Language.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.
        /// </summary>
        public static string Energy {
            get {
                return ResourceManager.GetString("Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HP.
        /// </summary>
        public static string HP {
            get {
                return ResourceManager.GetString("HP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string RarityCommon {
            get {
                return ResourceManager.GetString("RarityCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holofoil Rare.
        /// </summary>
        public static string RarityHolofoilRare {
            get {
                return ResourceManager.GetString("RarityHolofoilRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare.
        /// </summary>
        public static string RarityRare {
            get {
                return ResourceManager.GetString("RarityRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncommon.
        /// </summary>
        public static string RarityUncommon {
            get {
                return ResourceManager.GetString("RarityUncommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string StageBasic {
            get {
                return ResourceManager.GetString("StageBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fase 1.
        /// </summary>
        public static string StageFase1 {
            get {
                return ResourceManager.GetString("StageFase1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fase 2.
        /// </summary>
        public static string StageFase2 {
            get {
                return ResourceManager.GetString("StageFase2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string TCGPokemonForceDark {
            get {
                return ResourceManager.GetString("TCGPokemonForceDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string TCGPokemonForceLight {
            get {
                return ResourceManager.GetString("TCGPokemonForceLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TCGPokemonForceNormal {
            get {
                return ResourceManager.GetString("TCGPokemonForceNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colorless.
        /// </summary>
        public static string TCGTypeColorless {
            get {
                return ResourceManager.GetString("TCGTypeColorless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darkness.
        /// </summary>
        public static string TCGTypeDarkness {
            get {
                return ResourceManager.GetString("TCGTypeDarkness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragon.
        /// </summary>
        public static string TCGTypeDragon {
            get {
                return ResourceManager.GetString("TCGTypeDragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fairy.
        /// </summary>
        public static string TCGTypeFairy {
            get {
                return ResourceManager.GetString("TCGTypeFairy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighting.
        /// </summary>
        public static string TCGTypeFighting {
            get {
                return ResourceManager.GetString("TCGTypeFighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire.
        /// </summary>
        public static string TCGTypeFire {
            get {
                return ResourceManager.GetString("TCGTypeFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grass.
        /// </summary>
        public static string TCGTypeGrass {
            get {
                return ResourceManager.GetString("TCGTypeGrass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lighting.
        /// </summary>
        public static string TCGTypeLighting {
            get {
                return ResourceManager.GetString("TCGTypeLighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metal.
        /// </summary>
        public static string TCGTypeMetal {
            get {
                return ResourceManager.GetString("TCGTypeMetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psychic.
        /// </summary>
        public static string TCGTypePsychic {
            get {
                return ResourceManager.GetString("TCGTypePsychic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        public static string TCGTypeWater {
            get {
                return ResourceManager.GetString("TCGTypeWater", resourceCulture);
            }
        }
    }
}
